name: CICD Pipeline check

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

             - name: Checkout the repo
               uses: actions/checkout@v3

             - name: Install NodeJs
               uses: actions/setup-node@v4
               with:
                node-version: "22"

             - name: Install Package
               run: npm install

             - name: Test the Applications
               run: npm run check
                 
                 
        
